spring:
  application:
    name: askaboutme
  ai:
    google:
      genai:
        api-key: REDACTED
        embedding:
          api-key: REDACTED
          text:
            model: text-embedding-004
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        max-document-batch-size: 5
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmind



